version: '3.1'

services:
  db:
    image: postgres
    container_name: uptime-postgres
    environment:
      POSTGRES_DB: uptimeChecker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asd!@#777
    ports:
      - "11440:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 100s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.9.12
    container_name: my-rabbitmq-container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5677:5672"  # RabbitMQ main port
      - "15677:15672"  # RabbitMQ management UI
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uptime-checker-backend
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "9090:9090"

volumes:
  db-data:

