version: '3.1'

services:
  db:
    image: postgres
    container_name: uptime-postgres
    environment:
      POSTGRES_DB: uptimeChecker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Asd!@#777
    ports:
      - "11433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.9.12
    container_name: my-rabbitmq-container
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5677:5672"  # RabbitMQ main port
      - "15677:15672"  # RabbitMQ management UI

volumes:
  db-data:
